name: Benoliel
favicon: null
layout_spectrum: 0.19477893831208348
typography_spectrum: 0.0597670606803149
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.40772377233952284
  lightness: 0.11507712514139712
  saturation: 0.7616777385119349
  rhythmicContrast: 0.9953726611565799
purpose: []
